export const ACTIVITY_LOG_KEY = 'activity_log';

export const ActivityEntityType = {
  CONTACT: 'contact',
  CONTACT_INFO: 'contact_info',
  LEAD: 'lead',
  FILTER: 'filter',
  MARKETING_CAMPAIGN: 'marketing_campaign',
  OUTREACH_MESSAGE: 'outreach_message',
  OUTREACH_SEQUENCE: 'outreach_sequence',
  ORGANISATION: 'organisation',
  ORGANISATION_MEMBER: 'organisation_member',
  ORGANISATION_INVITATION: 'organisation_invitation',
  FORM: 'form',
  FORM_FIELD: 'form_field',
  FORM_COMPLETION: 'form_completion',
  REMINDER: 'reminder',
  INTEGRATION: 'integration',
  SENDER_PROFILE: 'sender_profile',
  MESSAGE_TEMPLATE: 'message_template',
  CONTACT_LIST: 'contact_list',
  SCORING_INSTRUCTION: 'scoring_instruction',
  AUDIENCE_ANALYSIS: 'audience_analysis',
  EMAIL_SEND_LIMIT: 'email_send_limit',
  SENDING_POLICY: 'sending_policy',
  SENDING_POLICY_STAGE: 'sending_policy_stage',
  CAMPAIGN_INTEGRATION: 'campaign_integration',
} as const;

export type ActivityEntityType =
  (typeof ActivityEntityType)[keyof typeof ActivityEntityType];

export const ActivityAction = {
  CREATED: 'created',
  UPDATED: 'updated',
  DELETED: 'deleted',
  DUPLICATED: 'duplicated',
  CONVERTED_FROM_LEAD: 'converted_from_lead',
  STATUS_UPDATED: 'status_updated',
  TAGS_UPDATED: 'tags_updated',
  BULK_DELETED: 'bulk_deleted',
  ENRICHED: 'enriched',
  BULK_ENRICHED: 'bulk_enriched',
  SCORED: 'scored',
  BULK_SCORED: 'bulk_scored',
  EMAIL_SCRAPED: 'email_scraped',
  DRAFT_GENERATED: 'draft_generated',
  BULK_DRAFT_GENERATED: 'bulk_draft_generated',
  NOTE_ADDED: 'note_added',
  CALL_LOGGED: 'call_logged',
  MEETING_LOGGED: 'meeting_logged',
  EMAIL_LOGGED: 'email_logged',
  SMS_LOGGED: 'sms_logged',
  STARTED: 'started',
  SCHEDULED: 'scheduled',
  CANCELLED: 'cancelled',
  RERUN: 'rerun',
  DRAFTS_SENT: 'drafts_sent',
  DRAFT_MESSAGE_SENT: 'draft_message_sent',
  DRAFT_MESSAGE_DELETED: 'draft_message_deleted',
  AI_GENERATED: 'ai_generated',
  MESSAGE_CREATED: 'message_created',
  MESSAGE_DRAFTED: 'message_drafted',
  MESSAGE_UPDATED: 'message_updated',
  MESSAGE_SENT: 'message_sent',
  MESSAGE_DELETED: 'message_deleted',
  SEQUENCE_CREATED: 'sequence_created',
  SEQUENCE_ASSIGNED: 'sequence_assigned',
  RUN_STARTED: 'run_started',
  RUN_STOPPED: 'run_stopped',
  ANALYSIS_CREATED: 'analysis_created',
  ANALYSIS_DELETED: 'analysis_deleted',
  SWITCHED: 'switched',
  MEMBER_ROLE_UPDATED: 'member_role_updated',
  MEMBER_REMOVED: 'member_removed',
  INVITATION_CREATED: 'invitation_created',
  INVITATION_RESENT: 'invitation_resent',
  INVITATION_REVOKED: 'invitation_revoked',
  INVITATION_ACCEPTED: 'invitation_accepted',
  CONTACTS_ADDED: 'contacts_added',
  CONTACTS_REMOVED: 'contacts_removed',
  CONTACTS_BULK_ADDED: 'contacts_bulk_added',
  KEY_CREATED: 'key_created',
  KEY_UPDATED: 'key_updated',
  KEY_DELETED: 'key_deleted',
  SMTP_ACCOUNT_CREATED: 'smtp_account_created',
  RESEND_ACCOUNT_CREATED: 'resend_account_created',
  DOMAIN_ADDED: 'domain_added',
  DOMAIN_UPDATED: 'domain_updated',
  DOMAIN_DELETED: 'domain_deleted',
  DEFAULT_DOMAIN_SET: 'default_domain_set',
  DEFAULT_ACCOUNT_SET: 'default_account_set',
  ACCOUNT_TITLE_UPDATED: 'account_title_updated',
  COMPLETED: 'completed',
  REORDERED: 'reordered',
  CREATED_FROM_CAMPAIGN: 'created_from_campaign',
  CREATED_FROM_MESSAGE: 'created_from_message',
  ASSIGNED: 'assigned',
  PAUSED: 'paused',
  RESUMED: 'resumed',
  REMOVED: 'removed',
} as const;

export type ActivityAction =
  (typeof ActivityAction)[keyof typeof ActivityAction];
