export const ORGANISATION_TIMEZONES = [
    'UTC',
    'Europe/London',
    'Europe/Dublin',
    'Europe/Lisbon',
    'Europe/Paris',
    'Europe/Berlin',
    'Europe/Rome',
    'Europe/Madrid',
    'Europe/Amsterdam',
    'Europe/Stockholm',
    'Europe/Vienna',
    'Europe/Prague',
    'Europe/Warsaw',
    'Europe/Brussels',
    'Europe/Zagreb',
    'Europe/Copenhagen',
    'Europe/Budapest',
    'Europe/Luxembourg',
    'Europe/Malta',
    'Europe/Bratislava',
    'Europe/Ljubljana',
    'Europe/Sofia',
    'Asia/Nicosia',
    'Europe/Tallinn',
    'Europe/Helsinki',
    'Europe/Athens',
    'Europe/Riga',
    'Europe/Vilnius',
    'Europe/Bucharest',
] as const;

export type OrganisationTimezone = (typeof ORGANISATION_TIMEZONES)[number];
