export const ApiRoutes = {
    auth: {
        email: {
            login: "/auth/email/login",
            register: "/auth/email/register",
            refresh_token: "/auth/email/refresh-token",
            admin_login_to_account: (account_uuid: string) => `/auth/email/${account_uuid}/admin-login`,
            forgot_password: "/auth/forgot-password",
            reset_password: "/auth/reset-password",
            verify_email: "/auth/verify-email",
            resend_verification_email: "/auth/resend-verification-email",
        },
    },
    users: {
        prefix: "/users",
        me: "/users/me",
        change_password: "/users/me/password",
    },
    google_maps: {
        timezone: "/google-maps/timezone",
    },
    leads: {
        prefix: "/leads",
        list: "/leads",
        get: (uuid: string) => `/leads/${uuid}`,
        enrichments: (uuid: string) => `/leads/${uuid}/enrichments`,
        update: (uuid: string) => `/leads/${uuid}`,
        remove: (uuid: string) => `/leads/${uuid}`,
        enrich: (uuid: string) => `/leads/${uuid}/enrich`,
        bulk_enrich: "/leads/bulk-enrich",
    },
    contacts: {
        prefix: "/contacts",
        list: "/contacts",
        tags: "/contacts/tags",
        create: "/contacts",
        get: (uuid: string) => `/contacts/${uuid}`,
        update: (uuid: string) => `/contacts/${uuid}`,
        remove: (uuid: string) => `/contacts/${uuid}`,
        update_status: (uuid: string) => `/contacts/${uuid}/status`,
        update_tags: (uuid: string) => `/contacts/${uuid}/tags`,
        list_info: (uuid: string) => `/contacts/${uuid}/info`,
        create_info: (uuid: string) => `/contacts/${uuid}/info`,
        update_info: (uuid: string, infoUuid: string) => `/contacts/${uuid}/info/${infoUuid}`,
        remove_info: (uuid: string, infoUuid: string) => `/contacts/${uuid}/info/${infoUuid}`,
        add_note: (uuid: string) => `/contacts/${uuid}/notes`,
        log_call: (uuid: string) => `/contacts/${uuid}/calls`,
        log_meeting: (uuid: string) => `/contacts/${uuid}/meetings`,
        log_email: (uuid: string) => `/contacts/${uuid}/emails`,
        log_sms: (uuid: string) => `/contacts/${uuid}/sms`,
        interactions: (uuid: string) => `/contacts/${uuid}/interactions`,
        score: (uuid: string) => `/contacts/${uuid}/score`,
        draft_messages: (uuid: string) => `/contacts/${uuid}/draft-messages`,
        ai_draft_message: "/contacts/ai-draft-message",
        enrich: (uuid: string) => `/contacts/${uuid}/enrich`,
        enrichments: (uuid: string) => `/contacts/${uuid}/enrichments`,
        bulk_score: "/contacts/bulk-score",
        bulk_enrich: "/contacts/bulk-enrich",
        bulk_scrape_emails: "/contacts/bulk-scrape-emails",
        bulk_ai_draft_messages: "/contacts/bulk-ai-draft-messages",
        bulk_delete: "/contacts/bulk-delete",
        messages: (uuid: string) => `/contacts/${uuid}/messages`,
        from_lead: (lead_uuid: string) => `/contacts/from-lead/${lead_uuid}`,
    },
    outreach: {
        list_messages: "/outreach/messages",
        create_draft: "/outreach/messages/draft",
        create_and_send: "/outreach/messages",
        update_message: (uuid: string) => `/outreach/messages/${uuid}`,
        send_message: (uuid: string) => `/outreach/messages/${uuid}/send`,
        delete_message: (uuid: string) => `/outreach/messages/${uuid}`,
    },
    dashboard: {
        prefix: "/dashboard",
        stats: "/dashboard/stats",
        top_contacts: "/dashboard/top-contacts",
        pending_drafts: "/dashboard/pending-drafts",
    },
    filters: {
        prefix: "/filters",
        list: "/filters",
        create: "/filters",
        get: (uuid: string) => `/filters/${uuid}`,
        update: (uuid: string) => `/filters/${uuid}`,
        remove: (uuid: string) => `/filters/${uuid}`,
        run: (uuid: string) => `/filters/${uuid}/run`,
        stop: (uuid: string) => `/filters/${uuid}/stop`,
        jobs: (uuid: string) => `/filters/${uuid}/jobs`,
        stats: (uuid: string) => `/filters/${uuid}/stats`,
        analyses: (uuid: string) => `/filters/${uuid}/analyses`,
        analysis: (filterUuid: string, analysisUuid: string) =>
            `/filters/${filterUuid}/analyses/${analysisUuid}`,
    },
    gemi: {
        prefectures: "/gemi/prefectures",
        legal_types: "/gemi/legal-types",
        statuses: "/gemi/statuses",
    },
    scoring_instructions: {
        prefix: "/scoring-instructions",
        list: "/scoring-instructions",
        create: "/scoring-instructions",
        get: (uuid: string) => `/scoring-instructions/${uuid}`,
        update: (uuid: string) => `/scoring-instructions/${uuid}`,
        remove: (uuid: string) => `/scoring-instructions/${uuid}`,
    },
    sender_profiles: {
        prefix: "/sender-profiles",
        list: "/sender-profiles",
        create: "/sender-profiles",
        get: (uuid: string) => `/sender-profiles/${uuid}`,
        update: (uuid: string) => `/sender-profiles/${uuid}`,
        remove: (uuid: string) => `/sender-profiles/${uuid}`,
    },
    saved_contact_filters: {
        prefix: "/saved-contact-filters",
        list: "/saved-contact-filters",
        create: "/saved-contact-filters",
        get: (uuid: string) => `/saved-contact-filters/${uuid}`,
        update: (uuid: string) => `/saved-contact-filters/${uuid}`,
        remove: (uuid: string) => `/saved-contact-filters/${uuid}`,
    },
    integrations: {
        prefix: "/integrations",
        list: "/integrations",
        createKey: (provider: string) => `/integrations/${provider}/keys`,
        createSmtpAccount: "/integrations/SMTP/accounts",
        setDefaultAccount: (provider: string) =>
            `/integrations/${provider}/default-account`,
        updateAccount: (provider: string, account: string) =>
            `/integrations/${provider}/accounts/${encodeURIComponent(account)}`,
        updateKey: (uuid: string) => `/integrations/keys/${uuid}`,
        removeKey: (uuid: string) => `/integrations/keys/${uuid}`,
    },
    admin: {
        batch_jobs: "/admin/batch-jobs",
        queues: "/admin/queues",
        system_status: "/admin/system-status",
        email_validation_backfill: "/admin/email-validation-backfill",
    },
    reminders: {
        prefix: "/reminders",
        list: "/reminders",
        stats: "/reminders/stats",
        create: "/reminders",
        get: (uuid: string) => `/reminders/${uuid}`,
        update: (uuid: string) => `/reminders/${uuid}`,
        complete: (uuid: string) => `/reminders/${uuid}/complete`,
        remove: (uuid: string) => `/reminders/${uuid}`,
    },
    bulk_jobs: {
        prefix: "/bulk-jobs",
        list: "/bulk-jobs",
        get: (uuid: string) => `/bulk-jobs/${uuid}`,
    },
    message_templates: {
        prefix: "/message-templates",
        list: "/message-templates",
        create: "/message-templates",
        get: (uuid: string) => `/message-templates/${uuid}`,
        update: (uuid: string) => `/message-templates/${uuid}`,
        remove: (uuid: string) => `/message-templates/${uuid}`,
        ai_generate: "/message-templates/ai/generate",
        from_campaign: (campaignUuid: string) => `/message-templates/from-campaign/${campaignUuid}`,
        from_message: (messageUuid: string) => `/message-templates/from-message/${messageUuid}`,
    },
    sequences: {
        prefix: "/sequences",
        list: "/sequences",
        create: "/sequences",
        get: (uuid: string) => `/sequences/${uuid}`,
        update: (uuid: string) => `/sequences/${uuid}`,
        remove: (uuid: string) => `/sequences/${uuid}`,
        activate: (uuid: string) => `/sequences/${uuid}/activate`,
        archive: (uuid: string) => `/sequences/${uuid}/archive`,
        add_step: (uuid: string) => `/sequences/${uuid}/steps`,
        update_step: (uuid: string, stepUuid: string) => `/sequences/${uuid}/steps/${stepUuid}`,
        remove_step: (uuid: string, stepUuid: string) => `/sequences/${uuid}/steps/${stepUuid}`,
        reorder_steps: (uuid: string) => `/sequences/${uuid}/steps/reorder`,
        enroll: (uuid: string) => `/sequences/${uuid}/enroll`,
        enroll_bulk: (uuid: string) => `/sequences/${uuid}/enroll-bulk`,
        enrollments: (uuid: string) => `/sequences/${uuid}/enrollments`,
        cancel_enrollment: (uuid: string, enrollmentUuid: string) =>
            `/sequences/${uuid}/enrollments/${enrollmentUuid}/cancel`,
    },
    marketing_campaigns: {
        prefix: "/marketing-campaigns",
        list: "/marketing-campaigns",
        create: "/marketing-campaigns",
        get: (uuid: string) => `/marketing-campaigns/${uuid}`,
        update: (uuid: string) => `/marketing-campaigns/${uuid}`,
        remove: (uuid: string) => `/marketing-campaigns/${uuid}`,
        contacts: (uuid: string) => `/marketing-campaigns/${uuid}/contacts`,
        preview_contacts: (uuid: string) => `/marketing-campaigns/${uuid}/preview-contacts`,
        start: (uuid: string) => `/marketing-campaigns/${uuid}/start`,
        schedule: (uuid: string) => `/marketing-campaigns/${uuid}/schedule`,
        cancel: (uuid: string) => `/marketing-campaigns/${uuid}/cancel`,
        rerun: (uuid: string) => `/marketing-campaigns/${uuid}/rerun`,
        duplicate: (uuid: string) => `/marketing-campaigns/${uuid}/duplicate`,
        ai_generate: (uuid: string) => `/marketing-campaigns/${uuid}/ai/generate`,
        send_drafts: (uuid: string) => `/marketing-campaigns/${uuid}/send-drafts`,
        draft_messages: (uuid: string) => `/marketing-campaigns/${uuid}/draft-messages`,
        delete_draft_message: (campaignUuid: string, messageUuid: string) =>
            `/marketing-campaigns/${campaignUuid}/draft-messages/${messageUuid}`,
        send_draft_message: (campaignUuid: string, messageUuid: string) =>
            `/marketing-campaigns/${campaignUuid}/draft-messages/${messageUuid}/send`,
    },
    forms: {
        list: '/forms',
        create: '/forms',
        get: (uuid: string) => `/forms/${uuid}`,
        update: (uuid: string) => `/forms/${uuid}`,
        remove: (uuid: string) => `/forms/${uuid}`,
        duplicate: (uuid: string) => `/forms/${uuid}/duplicate`,
        createField: (formUuid: string) => `/forms/${formUuid}/fields`,
        updateField: (formUuid: string, fieldUuid: string) => `/forms/${formUuid}/fields/${fieldUuid}`,
        removeField: (formUuid: string, fieldUuid: string) => `/forms/${formUuid}/fields/${fieldUuid}`,
        reorderFields: (formUuid: string) => `/forms/${formUuid}/fields/reorder`,
        listCompletions: (formUuid: string) => `/forms/${formUuid}/completions`,
        createCompletion: (formUuid: string) => `/forms/${formUuid}/completions`,
        getCompletion: (formUuid: string, completionUuid: string) =>
            `/forms/${formUuid}/completions/${completionUuid}`,
        updateCompletion: (formUuid: string, completionUuid: string) =>
            `/forms/${formUuid}/completions/${completionUuid}`,
        removeCompletion: (formUuid: string, completionUuid: string) =>
            `/forms/${formUuid}/completions/${completionUuid}`,
        contactCompletions: (contactUuid: string) => `/form-completions/contact/${contactUuid}`,
    },
    contact_lists: {
        list: "/contact-lists",
        create: "/contact-lists",
        get: (uuid: string) => `/contact-lists/${uuid}`,
        update: (uuid: string) => `/contact-lists/${uuid}`,
        remove: (uuid: string) => `/contact-lists/${uuid}`,
        contacts: (uuid: string) => `/contact-lists/${uuid}/contacts`,
        add_contacts: (uuid: string) => `/contact-lists/${uuid}/contacts`,
        bulk_add_contacts: (uuid: string) => `/contact-lists/${uuid}/contacts/bulk`,
        bulk_remove_contacts: (uuid: string) => `/contact-lists/${uuid}/contacts/bulk-remove`,
        remove_contact: (listUuid: string, contactUuid: string) =>
            `/contact-lists/${listUuid}/contacts/${contactUuid}`,
        stats: (uuid: string) => `/contact-lists/${uuid}/stats`,
        analyses: (uuid: string) => `/contact-lists/${uuid}/analyses`,
        analysis: (listUuid: string, analysisUuid: string) =>
            `/contact-lists/${listUuid}/analyses/${analysisUuid}`,
    },
    ai_usage: {
        list: "/ai-usage",
        summary: "/ai-usage/summary",
    },
    apify_usage: {
        list: "/apify-usage",
        summary: "/apify-usage/summary",
    },
    activity_logs: {
        list: "/activity-logs",
    },
    organisations: {
        list: "/organisations",
        create: "/organisations",
        current: "/organisations/current",
        update: (uuid: string) => `/organisations/${uuid}`,
        remove: (uuid: string) => `/organisations/${uuid}`,
        switch: (uuid: string) => `/organisations/${uuid}/switch`,
        members: (uuid: string) => `/organisations/${uuid}/members`,
        updateMember: (uuid: string, userUuid: string) =>
            `/organisations/${uuid}/members/${userUuid}`,
        removeMember: (uuid: string, userUuid: string) =>
            `/organisations/${uuid}/members/${userUuid}`,
        invitations: (uuid: string) => `/organisations/${uuid}/invitations`,
        createInvitation: (uuid: string) => `/organisations/${uuid}/invitations`,
        resendInvitation: (uuid: string, invitationUuid: string) =>
            `/organisations/${uuid}/invitations/${invitationUuid}/resend`,
        revokeInvitation: (uuid: string, invitationUuid: string) =>
            `/organisations/${uuid}/invitations/${invitationUuid}`,
        previewInvitation: (token: string) => `/organisations/invitations/${token}`,
        acceptInvitation: (token: string) => `/organisations/invitations/${token}/accept`,
    },
    messaging_goals: {
        prefix: "/messaging-goals",
        me: "/messaging-goals/me",
        bulk: "/messaging-goals/bulk",
        leaderboard: "/messaging-goals/leaderboard",
        achievements: "/messaging-goals/achievements",
        achievementSeen: (uuid: string) => `/messaging-goals/achievements/${uuid}/seen`,
        update: (uuid: string) => `/messaging-goals/${uuid}`,
        remove: (uuid: string) => `/messaging-goals/${uuid}`,
    },
    email_send_limits: {
        list: "/email-send-limits",
        upsert: "/email-send-limits",
        remove: (uuid: string) => `/email-send-limits/${uuid}`,
    },
    sending_policies: {
        list: "/sending-policies",
        create: "/sending-policies",
        get: (uuid: string) => `/sending-policies/${uuid}`,
        update: (uuid: string) => `/sending-policies/${uuid}`,
        remove: (uuid: string) => `/sending-policies/${uuid}`,
        add_stage: (uuid: string) => `/sending-policies/${uuid}/stages`,
        update_stage: (uuid: string, stageUuid: string) =>
            `/sending-policies/${uuid}/stages/${stageUuid}`,
        remove_stage: (uuid: string, stageUuid: string) =>
            `/sending-policies/${uuid}/stages/${stageUuid}`,
        reorder_stages: (uuid: string) => `/sending-policies/${uuid}/stages/reorder`,
        preview: (uuid: string) => `/sending-policies/${uuid}/preview`,
    },
    campaign_integrations: {
        list: (campaignUuid: string) => `/marketing-campaigns/${campaignUuid}/integrations`,
        assign: (campaignUuid: string) => `/marketing-campaigns/${campaignUuid}/integrations`,
        update_status: (campaignUuid: string, ciUuid: string) =>
            `/marketing-campaigns/${campaignUuid}/integrations/${ciUuid}`,
        remove: (campaignUuid: string, ciUuid: string) =>
            `/marketing-campaigns/${campaignUuid}/integrations/${ciUuid}`,
        capacity: (campaignUuid: string, ciUuid: string) =>
            `/marketing-campaigns/${campaignUuid}/integrations/${ciUuid}/capacity`,
    },
}