export const Routes = {
    root: "/",
    unsubscribe: "/unsubscribe/:token",
    auth: {
        sign_in: "/auth/sign-in",
        sign_up: "/auth/sign-up",
        invite: "/auth/invite/:token",
    },
    admin: {
        users: "/admin/users",
        alerts: "/admin/alerts",
    },
    dashboard: {
        root: "/dashboard",
        leads_directory: "/dashboard/leads-directory",
        leads_directory_detail: "/dashboard/leads-directory/:uuid",
        leads: "/dashboard/leads",
        contacts: "/dashboard/contacts",
        contacts_detail: "/dashboard/contacts/:uuid",
        filters: "/dashboard/filters",
        filters_new: "/dashboard/filters/new",
        filters_scoring_instructions: "/dashboard/filters/scoring-instructions",
        filters_detail: "/dashboard/filters/:uuid",
        filters_detail_tab_query: "tab",
        map: "/dashboard/map",
        analytics: "/dashboard/analytics",
        settings: "/dashboard/settings",
        settings_account: "/dashboard/settings/account",
        settings_usage: "/dashboard/settings/usage",
        settings_organisation: "/dashboard/settings/organisation",
        settings_activity: "/dashboard/settings/activity",
        sender_profiles: "/dashboard/sender-profiles",
        integrations: "/dashboard/integrations",
        campaigns: "/dashboard/campaigns",
        campaigns_new: "/dashboard/campaigns/new",
        campaigns_detail: "/dashboard/campaigns/:uuid",
        campaigns_edit: "/dashboard/campaigns/:uuid/edit",
        send_history: "/dashboard/send-history",
        mail_tester: "/dashboard/mail-tester",
        mxtoolbox: "/dashboard/domain-health",
        message_templates: "/dashboard/message-templates",
        sequences: "/dashboard/sequences",
        sequences_new: "/dashboard/sequences/new",
        sequences_edit: "/dashboard/sequences/:uuid/edit",
        reminders: "/dashboard/reminders",
        jobs: "/dashboard/jobs",
        batch_jobs: "/dashboard/batch-jobs",
        goals: "/dashboard/goals",
        forms: "/dashboard/forms",
        forms_detail: "/dashboard/forms/:uuid",
        lists: "/dashboard/lists",
        lists_detail: "/dashboard/lists/:uuid",
        lists_detail_tab_query: "tab",
        admin_controls: "/dashboard/admin",
        admin_system_status: "/dashboard/admin/system-status",
    },
};

export const FilterDetailTabIds = {
    FILTER: "filter",
    CONTACTS: "contacts",
    JOBS: "jobs",
    ANALYTICS: "analytics",
} as const;

export const ListDetailTabIds = {
    SUBLISTS: "sublists",
    CONTACTS: "contacts",
    ANALYTICS: "analytics",
} as const;
